[workspace]
members = [
    "host",
    "relay",
    "methods/guest",
    "core"
]
default-members = ["host", "relay"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.75"
bech32 = "0.9.0"
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "release-0.19" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", branch = "release-0.19" }
derive_more = { version = "0.99" }
enum-iterator = "1.2"
ethers = {version = "=2.0.8"}
ethabi = "18.0.0"
fuel-crypto = { git = "https://github.com/DefiCake/fuel-vm", rev="bf8196df278cf03cd15b453e5837f88914c10ec4",  default-features = false}
fuel-storage = { git = "https://github.com/DefiCake/fuel-vm", rev="bf8196df278cf03cd15b453e5837f88914c10ec4",  default-features = false}
fuel-tx = { git = "https://github.com/DefiCake/fuel-vm", rev="bf8196df278cf03cd15b453e5837f88914c10ec4", default-features = false, features = ["builder"]}
fuel-types = { git = "https://github.com/DefiCake/fuel-vm", rev="bf8196df278cf03cd15b453e5837f88914c10ec4",  default-features = false}
fuel-vm = { git = "https://github.com/DefiCake/fuel-vm", rev="bf8196df278cf03cd15b453e5837f88914c10ec4",  default-features = false, features = ["serde", "alloc"]}
hex = "0.4.3"
itertools = "0.10"
primitive-types = "0.12"
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.19" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.19", default-features = false }
methods = { path = "./methods", package = "methods" }
postcard = "1.0"
prover-core = { path = "./core" }
serde = {version = "1.0.188", default-features = false}
serde_json = "1.0.104"
serde_with = "1.11"
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
