[workspace]
members = [
    "host",
    "relay",
    "methods/guest",
    "core"
]
default-members = ["host", "relay"]

[workspace.dependencies]
anyhow = "1.0.75"
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
ethers = {version = "=2.0.8"}
ethabi = "18.0.0"
fuel-crypto = { git = "https://github.com/DefiCake/fuel-vm", rev="1e44c68571def6deac1048de57ab083fd6e4fdda",  default-features = false}
fuel-storage = { git = "https://github.com/DefiCake/fuel-vm", rev="1e44c68571def6deac1048de57ab083fd6e4fdda",  default-features = false}
fuel-tx = { git = "https://github.com/DefiCake/fuel-vm", rev="1e44c68571def6deac1048de57ab083fd6e4fdda", default-features = false, features = ["builder"]}
fuel-types = { git = "https://github.com/DefiCake/fuel-vm", rev="1e44c68571def6deac1048de57ab083fd6e4fdda",  default-features = false}
fuel-vm = { git = "https://github.com/DefiCake/fuel-vm", rev="1e44c68571def6deac1048de57ab083fd6e4fdda",  default-features = false, features = ["serde", "alloc"]}
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.17", default-features = false }
methods = { path = "./methods", package = "methods" }
prover-core = { path = "./core" }
serde = {version = "1.0.188", default-features = false}
serde_json = "1.0.104"
# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
