[workspace]
name="fuel-prover"
members = [
    "host",
    "relay",
    "methods/guest",
]
default-members = ["host", "relay"]

[workspace.dependencies]
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
ethers = {version = "=2.0.8"}
ethabi = "18.0.0"
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.17" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.17", default-features = false }
methods = { path = "./methods", package = "methods" }
serde = {version = "1.0.188", default-features = false}
serde_json = "1.0.104"
fuel-crypto = {path = "/Users/mad/fuel/vm/fuel-crypto", default-features = false}
# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
