[patch.'https://github.com/gakonst/ethers-rs']
ethers = {version = '=2.0.8'}
ethers-addressbook = {version = '=2.0.8'}
ethers-core = {version = '=2.0.8'}
ethers-contract = {version = '=2.0.8'}
ethers-contract-abigen = {version = '=2.0.8'}
ethers-providers = {version = '=2.0.8'}
ethers-signers = {version = '=2.0.8'}
ethers-middleware = {version = '=2.0.8'}
ethers-etherscan = {version = '=2.0.8'}
ethers-solc = {version = '=2.0.8'}

[build]
rustflags = [
    "-Dclippy::correctness",
    "-Dclippy::suspicious",
    "-Wclippy::complexity",
    "-Wclippy::perf",
    "-Wclippy::style",
    "-Wclippy::unwrap_used",
    "-Wclippy::expect_used",
    "-Dclippy::needless_return",
    "-Dbad_style",
    "-Dbare_trait_objects",
    "-Ddead_code",
    "-Dimproper_ctypes",
    "-Dno_mangle_generic_items",
    "-Dnon_shorthand_field_patterns",
    "-Doverflowing_literals",
    "-Dpath_statements",
    "-Dpatterns_in_fns_without_body",
    "-Dprivate_in_public",
    "-Dtrivial_casts",
    "-Dtrivial_numeric_casts",
    "-Dunconditional_recursion",
    "-Dunused_allocation",
    "-Dunused_comparisons",
    "-Wunused_extern_crates",
    "-Dunused_parens",
    "-Dwhile_true",
]

[net]
git-fetch-with-cli = true
